/*

 BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\gbdk\tools\gbtd22\tiles test.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BgWidth 32
#define BgHeight 32
#define BgBank 0

extern const unsigned char Background[];

/* End of BG.H */
